### ISSUE TITLE
Error when trying to add email to notify list

### ISSUE THREAD

**Issue by joshmosh** [CivilServiceUSA/website#1]
When I try to add my email to the notify list I get the following error:

```
Refused to load https://services.us14.list-manage.com/subscribe/post-json?u=158de27f713f7ed26783835cd&id=21d91c33fe&c=jQuery1124079068603822241_1486760331053&EMAIL=joshminnich%40gmail.com&_=1486760331054 because it does not appear in the script-src directive of the Content Security Policy.
```

**Comment by manifestinteractive** [comment]
I think this issue might be for this project, correct ?

https://github.com/CivilServiceUSA/coming-soon-website

I will go ahead and add that though, thanks for letting me know :)

**Comment by manifestinteractive** [comment]
This should be resolved now

<img width="499" alt="screen shot 2017-02-10 at 9 20 24 pm" src="https://cloud.githubusercontent.com/assets/508411/22850401/c950de8a-efd6-11e6-8fc6-d78cdd6fb92a.png">

**Comment by joshmosh** [comment]
Doh! I didn't notice the other repo. Thanks for fixing @manifestinteractive.
